theme: jekyll-theme-leap-day

baseurl: "/"
name: name of my website
description: This website is a personal webpage of Prof. Jicheng Hu @ Wuhan University

lsi: false
safe: true
#source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

